### ISSUE TITLE
[Error] Upgrade AGP version from 7.4.2 to 8.0.0

### ISSUE THREAD

**Issue by luckyzyx** [joomcode/paranoid#7]
An error occurred when I updated the project AGP.
Then I found in idea.log that the source of the error was paranoid.
When I annotate the plug-in and update the AGP normally, could you please fix this problem? Thank you.

```
Caused by: java.lang.NoClassDefFoundError: com/android/build/api/artifact/MultipleArtifact$ALL_CLASSES_DIRS
	at com.joom.paranoid.plugin.ParanoidPlugin.registerParanoidTransformTask(ParanoidPlugin.kt:137)
	at com.joom.paranoid.plugin.ParanoidPlugin.access$registerParanoidTransformTask(ParanoidPlugin.kt:31)
	at com.joom.paranoid.plugin.ParanoidPlugin$registerParanoidWithVariantApi$1$1.invoke(ParanoidPlugin.kt:103)
	at com.joom.paranoid.plugin.ParanoidPlugin$registerParanoidWithVariantApi$1$1.invoke(ParanoidPlugin.kt:101)
	at com.android.build.api.extension.impl.AndroidComponentsExtensionImpl$onVariants$1.execute(AndroidComponentsExtensionImpl.kt:72)
	at com.android.build.api.extension.impl.AndroidComponentsExtensionImpl$onVariants$1.execute(AndroidComponentsExtensionImpl.kt:71)
	at com.android.build.api.extension.impl.OperationsRegistrar.executeOperations(OperationsRegistrar.kt:65)
	at com.android.build.gradle.internal.VariantManager.createVariantsFromCombination(VariantManager.kt:890)
	at com.android.build.gradle.internal.VariantManager.computeVariants(VariantManager.kt:219)
	at com.android.build.gradle.internal.VariantManager.createVariants(VariantManager.kt:182)
	at com.android.build.gradle.internal.plugins.BasePlugin.createAndroidTasks(BasePlugin.kt:689)
	at com.android.build.gradle.internal.plugins.BasePlugin$createTasks$2$1.call(BasePlugin.kt:580)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:69)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:54)
	at com.android.build.gradle.internal.profile.AnalyticsResourceManager.recordBlockAtConfiguration(AnalyticsResourceManager.kt:223)
	at com.android.build.gradle.internal.profile.AnalyticsConfiguratorService.recordBlock(AnalyticsConfiguratorService.kt:83)
	at com.android.build.gradle.internal.plugins.BasePlugin$createTasks$2.accept(BasePlugin.kt:575)
	at com.android.build.gradle.internal.plugins.BasePlugin$createTasks$2.accept(BasePlugin.kt:572)
	at com.android.build.gradle.internal.crash.CrashReporting$afterEvaluate$1.execute(crash_reporting.kt:37)
	at com.android.build.gradle.internal.crash.CrashReporting$afterEvaluate$1.execute(crash_reporting.kt:35)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:171)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction.execute(DefaultListenerBuildOperationDecorator.java:168)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:97)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:85)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:43)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:257)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:164)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:83)
	... 175 more
Caused by: java.lang.ClassNotFoundException: com.android.build.api.artifact.MultipleArtifact$ALL_CLASSES_DIRS
	... 212 more
2023-05-02 18:47:28,923 [ 566098]   INFO - #c.a.t.i.g.p.s.GradleSyncStateHolder$SyncStateUpdater - onFailure(RESOLVE_PROJECT:6, com.intellij.openapi.externalSystem.model.ExternalSystemException: Unable to load class 'com.android.build.api.artifact.MultipleArtifact$ALL_CLASSES_DIRS'.

This is an unexpected error. Please file a bug containing the idea.log file.)
2023-05-02 18:47:28,923 [ 566098]   INFO - #c.a.t.i.g.p.s.GradleSyncStateHolder$SyncStateUpdaterService - stopTrackingTask(RESOLVE_PROJECT:6)
2023-05-02 18:47:28,923 [ 566098]   WARN - #c.a.t.i.g.p.s.GradleSyncStateHolder - Gradle sync failed in 656 ms. Unable to load class 'com.android.build.api.artifact.MultipleArtifact$ALL_CLASSES_DIRS'.

This is an unexpected error. Please file a bug containing the idea.log file.
2023-05-02 18:47:28,924 [ 566099]   WARN - #c.a.t.i.g.p.s.GradleSyncStateHolder - Unable to load class 'com.android.build.api.artifact.MultipleArtifact$ALL_CLASSES_DIRS'.

This is an unexpected error. Please file a bug containing the idea.log file.
com.intellij.openapi.externalSystem.model.ExternalSystemException: Unable to load class 'com.android.build.api.artifact.MultipleArtifact$ALL_CLASSES_DIRS'.

This is an unexpected error. Please file a bug containing the idea.log file.
```

**Comment by dkostyrev** [comment]
Thank you for the issue, we will add support of AGP 8.0 in near future.

**Comment by dkostyrev** [comment]
AGP 8.x will be supported in the next release
